version: '3.8'

services:
  postgres:
    image: ankane/pgvector
    container_name: asai_pg
    restart: unless-stopped
    environment:
      POSTGRES_DB: asai_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
      build:
        dockerfile: ./Dockerfile
        context: ./
      ports:
        - "8000:8000"

volumes:
  pgdata:
